#!/usr/bin/env python3
"""
Emit the four `Resources/UiStyles/*.style.json` recipes.

The split this establishes, and the reason SkinForge grew a `$base` key:

  STRUCTURE lives in authored `.states.json` files (Tools/design_*.py emits them, the Designer can
  open them). A recipe cannot turn a machined knob into a Tron ring — that is thirty properties of
  geometry, not a colour change.

  COLOUR lives here. A style's DARK mode names its authored files and says nothing else, so it
  rosters them byte-for-byte with no bake at all. Its LIGHT mode is the same hardware in a
  different room: identical geometry, identical patterns, identical shadows — only the palette
  moves. That is exactly the user's framing: "the same equipment on lights-on vs nightclub time."
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Assets" / "Resources" / "UiStyles"

# role -> skin-name suffix. Family-level $base covers the common case; these are the exceptions.
ROLE_BASE = {
    "pad": "Pad",
    "button.accent": "Accent", "button.hero": "Accent",
    "toggle.button": "ToggleBtn", "button.close": "Close", "lamp": "Lamp",
    "knob.hero": "KnobHero", "knob.small": "KnobSmall",
    "panel.faceplate": "Face", "panel.inset": "Inset",
    "display.well": "Well", "panel.backplane": "Back",
}
FAMILY_BASE = {"Button": "Button", "Knob": "Knob", "Slider": "Slider",
               "Toggle": "Pill", "Panel": "Face"}


# Recipes this script must NOT write any more: each has since been rebuilt somewhere else, and
# re-running this would silently throw that work away. Their blocks below are kept as history.
HAND_OWNED = {
    "Realistic": "the hand-edited Realistic.style.json (silver-hardware light mode, 2026-09-13)",
    "Neomorphic": "the hand-edited Neomorphic.style.json (NeoDark*/NeoLight* roster, 2026-09-13)",
    "Flat": "Tools/design_flat.py recipe (unlit, non-RM, 2026-09-13)",
    "Tron": "Tools/design_tron.py recipe (unlit, non-RM, neon tubes, 2026-09-14)",
}


def recipe(style, title, order, blurb, dark, light, light_recipe, shifts=None, prefix=None):
    """One style file. `dark`/`light` are the mode colour/palette blocks.

    `prefix` is the authored-skin name stem when it differs from the style id (the Neomorphic
    files are named Neo* — a style id is a user-facing word, a skin name is a filename)."""
    prefix = prefix or style
    families = {f: {"$base": prefix + suf} for f, suf in FAMILY_BASE.items()}
    roles = {r: {"$base": prefix + suf} for r, suf in ROLE_BASE.items()}

    doc = {
        "styleName": style, "title": title, "order": order,
        "author": "DrumSumDrum", "blurb": blurb,
        "stateShifts": shifts or {"Hover": 0.08, "Pressed": -0.10,
                                  "Active": 0.16, "Disabled": -0.22},
        "families": families,
        "roles": roles,
        "modes": {
            "dark": dark,
            "light": dict(light, **light_recipe),
        },
    }
    path = OUT / f"{style}.style.json"
    if style in HAND_OWNED:
        print(f"  -- {path.name} skipped (owned by {HAND_OWNED[style]})")
        return
    header = f"""// ═══════════════════════════════════════════════════════════════════════════
// {title.upper()} — {blurb}
//
// "$base" names the AUTHORED states.json each part is built from. The dark mode adds no
// overrides, so SkinForge rosters those files directly and bakes nothing — dark IS the authored
// look, byte for byte. The light mode is a pure recolour of the same geometry: every bevel,
// pattern, screw and shadow survives, because light/dark is a MODE of one style rather than two
// unrelated styles. The hardware doesn't change; the room does.
//
// Generated by Tools/build_recipes.py. Colours here and in Tools/design_*.py are the same
// palette — edit either and re-run, or edit the baked states.json in the Designer and stop
// caring that this file exists.
// ═══════════════════════════════════════════════════════════════════════════
"""
    path.write_text(header + json.dumps(doc, indent=2), encoding="utf-8")
    print(f"  -> {path.name}")


# ── REALISTIC ────────────────────────────────────────────────────────────────
# Light = the same rack under studio lighting: aluminium instead of graphite, cream plates, ink
# type, and the LEDs stop glowing because you cannot see a lit LED in a bright room.
recipe(
    "Realistic", "Realistic", 1,
    "Boutique rack gear. Brushed metal, real screws, lit from one lamp.",
    dark={
        "trackTheme": "Nebula",
        "blurb": "Lit at the club. Graphite faceplates, warm lamps, deep shadow.",
        "colors": {"face": "#2A2F36", "inset": "#1E2228", "backplane": "#111418",
                   "well": "#0A1822", "body": "#3D434B", "bodyAlt": "#2E343B",
                   "accent": "#4FD1E0", "line": "#4A5058", "hot": "#D2544A",
                   "lamp": "#6EE7A8", "mark": "#DCE2EA"},
        "palettes": {
            "ui": {"text": "#DCE2EA", "textDim": "#7B838E", "textFaint": "#525A64",
                   "accent": "#4FD1E0", "warn": "#FFB84D", "danger": "#FF6B6B", "ok": "#6EE7A8"},
            "surface": {"card": "#1E2228FA", "cardEdge": "#2E343B",
                        "divider": "#191D22", "scrim": "#000000B8"},
        },
    },
    light={
        "trackTheme": "Rosewater",
        "blurb": "Daylight studio. Aluminium, cream plates, ink-dark labels.",
        "colors": {"face": "#8C9298", "inset": "#7A8086", "backplane": "#61666C",
                   "well": "#9CADB6", "body": "#949AA1", "bodyAlt": "#7D838A",
                   "accent": "#0E7C8C", "line": "#8D949C", "hot": "#BC4A3E",
                   "lamp": "#2E9E67", "mark": "#1B1F26"},
        "palettes": {
            "ui": {"text": "#171B21", "textDim": "#4A525C", "textFaint": "#767E88",
                   "accent": "#0E7C8C", "warn": "#A4691B", "danger": "#B03A3A", "ok": "#2E7D50"},
            "surface": {"card": "#D6DADFFA", "cardEdge": "#A8AEB6",
                        "divider": "#BEC3CA", "scrim": "#2A2E34A0"},
        },
    },
    light_recipe={
        "families": {
            # Ambient up, emissive off: a bright room, not a dark one with the lamps turned up.
            "Button": {"_ButtonColor": "$body", "_LightingAmbient": 0.58,
                       "_IconColor": "$mark"},
            "Knob": {"_KnobColor": "$body", "_FillColor": "$inset", "_KnobNubColor": "$mark",
                     "_LineSublineFilledColor": "$accent",
                     "_LineSublineFilledRenderEmissive": 0.0,
                     "_LineSublineUnfilledColor": "#6A7078",
                     "_OuterMarksColorUnfilled": "$line",
                     "_OuterMarksColorFilled": "$accent",
                     "_OuterMarksMajorColorUnfilled": "$mark",
                     "_OuterMarksMajorColorFilled": "$accent",
                     "_KnobEdgeColor": "#6E757EA0", "_LightingAmbient": 0.58},
            "Slider": {"_HandleColor": "$body", "_BgColor": "$inset",
                       "_TrackColor": "#5F656C", "_TrackValueFilledColor": "$accent",
                       "_TrackValueUnfilledColor": "#6A7078",
                       "_TrackValueFilledRenderEmissive": 0.0, "_LightingAmbient": 0.58},
            "Toggle": {"_HandleColor": "$body", "_BgColor": "$inset",
                       "_TrackColor": "#5F656C", "_LightingAmbient": 0.58},
            "Panel": {"_PanelColor": "$face", "_PanelGradientColorA": "#989EA5",
                      "_PanelGradientColorB": "#7F858C", "_LightingAmbient": 0.74},
        },
        "roles": {
            "pad": {"_ButtonColor": "$bodyAlt"},
            "button.accent": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF"},
            "button.hero": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF"},
            "toggle.button": {"_ButtonColor": "$bodyAlt"},
            "button.close": {"_ButtonColor": "$bodyAlt"},
            "lamp": {"_ButtonColor": "#8C9891", "_IconColor": "$lamp"},
            "panel.inset": {"_PanelColor": "$inset", "_PanelGradientColorA": "#868C93",
                            "_PanelGradientColorB": "#6F757C"},
            "panel.backplane": {"_PanelColor": "$backplane",
                                "_PanelGradientColorA": "#6C7279",
                                "_PanelGradientColorB": "#585E65"},
            "display.well": {"_PanelColor": "$well", "_PanelRenderEmissive": 0.0,
                             "_PanelGradientColorA": "#AAB9C0",
                             "_PanelGradientColorB": "#8B99A0"},
        },
    },
)

# ── NEOMORPHIC ───────────────────────────────────────────────────────────────
# The whole style is one colour lit from one side, so light mode is genuinely just that colour
# changing — charcoal clay becomes warm plaster and every shadow keeps working.
recipe(
    "Neomorphic", "Neomorphic", 2,
    "Everything moulded from the same block. Soft shadow does all the work.",
    dark={
        "trackTheme": "Nebula",
        "blurb": "Charcoal clay. Everything moulded from the same block.",
        "colors": {"face": "#31353C", "inset": "#2C3037", "backplane": "#282C32",
                   "well": "#2A2E35", "body": "#31353C", "bodyAlt": "#2C3037",
                   "accent": "#37D6C4", "line": "#3A3F47", "hot": "#E8705F",
                   "lamp": "#7EE8B0", "mark": "#C7CFDA"},
        "palettes": {
            "ui": {"text": "#C7CFDA", "textDim": "#767E8A", "textFaint": "#535A64",
                   "accent": "#37D6C4", "warn": "#F0B457", "danger": "#E8705F", "ok": "#7EE8B0"},
            "surface": {"card": "#31353CFA", "cardEdge": "#3A3F47",
                        "divider": "#2A2E35", "scrim": "#14171BB8"},
        },
    },
    light={
        "trackTheme": "Rosewater",
        "blurb": "Warm plaster. The classic soft-UI look, done properly.",
        "colors": {"face": "#96979A", "inset": "#8E8F93", "backplane": "#85868A",
                   "well": "#9C9DA0", "body": "#96979A", "bodyAlt": "#8E8F93",
                   "accent": "#1FA898", "line": "#C6C2BC", "hot": "#D2543F",
                   "lamp": "#3FA877", "mark": "#3A3630"},
        "palettes": {
            "ui": {"text": "#3A3630", "textDim": "#7A756D", "textFaint": "#A29C93",
                   "accent": "#1FA898", "warn": "#B07A20", "danger": "#C24A38", "ok": "#3FA877"},
            "surface": {"card": "#E4E1DCFA", "cardEdge": "#CFCCC7",
                        "divider": "#D3CFC9", "scrim": "#3A3630A0"},
        },
    },
    light_recipe={
        "families": {
            # The shadow colour has to change too: a black shadow on plaster reads as dirt.
            "Button": {"_ButtonColor": "$body", "_LightingAmbient": 0.60,
                       "_IconColor": "#4A463F",
                       "_ButtonShadow1Color": "#585A5EAA", "_ButtonShadow2Color": "#64666988"},
            "Knob": {"_KnobColor": "$body", "_FillColor": "$face", "_KnobNubColor": "$mark",
                     "_LineSublineFilledColor": "$accent",
                     "_LineSublineUnfilledColor": "#85868A",
                     "_LineSublineGlowColor": "$accent",
                     "_LineSublineFilledRenderEmissive": 0.0,
                     "_LightingAmbient": 0.60,
                     "_KnobShadow1Color": "#585A5EAA", "_KnobShadow2Color": "#64666988"},
            "Slider": {"_HandleColor": "$body", "_BgColor": "$face",
                       "_TrackColor": "#85868A", "_TrackValueFilledColor": "$accent",
                       "_TrackValueUnfilledColor": "#85868A",
                       "_TrackValueFilledRenderEmissive": 0.0, "_LightingAmbient": 0.60,
                       "_HandleShadow1Color": "#585A5EAA", "_HandleShadow2Color": "#64666988"},
            "Toggle": {"_HandleColor": "$body", "_BgColor": "$face",
                       "_TrackColor": "#85868A", "_LightingAmbient": 0.60,
                       "_ToggleShadow1Color": "#585A5EAA", "_ToggleShadow2Color": "#64666988"},
            "Panel": {"_PanelColor": "$face", "_LightingAmbient": 0.74},
        },
        "roles": {
            "panel.inset": {"_PanelColor": "$inset"},
            "panel.backplane": {"_PanelColor": "$backplane"},
            "display.well": {"_PanelColor": "$well", "_PanelRenderEmissive": 0.0},
            "button.accent": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF"},
            "button.hero": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF"},
            "lamp": {"_ButtonColor": "$inset", "_IconColor": "#4A463F"},
        },
    },
    prefix="Neo",
)

# ── TRON ─────────────────────────────────────────────────────────────────────
# "Same lines, inverted floor" — the glow lines stay exactly where they are; the floor they are
# drawn on flips from black to white. Emissive comes off, because a glow on white is a smudge.
recipe(
    "Tron", "Tron", 3,
    "Unlit vector HUD. Bodies are black, everything you see is an edge.",
    dark={
        "trackTheme": "Grid",
        "blurb": "The grid at night. Cyan lines on a black floor.",
        "colors": {"face": "#070C12", "inset": "#050A0F", "backplane": "#02050A",
                   "well": "#03080E", "body": "#0A141C", "bodyAlt": "#0D1B26",
                   "accent": "#31E4F5", "line": "#128FA6", "hot": "#FF3E7F",
                   "lamp": "#5BFFB0", "mark": "#E8FDFF"},
        "palettes": {
            "ui": {"text": "#E8FDFF", "textDim": "#2E6472", "textFaint": "#1B4450",
                   "accent": "#31E4F5", "warn": "#FFC93E", "danger": "#FF3E7F", "ok": "#5BFFB0"},
            "surface": {"card": "#050A0FF2", "cardEdge": "#128FA6",
                        "divider": "#0C2A33", "scrim": "#00060AC0"},
        },
    },
    light={
        "trackTheme": "Grid",
        "blurb": "The grid in daylight. Same lines, inverted floor.",
        "colors": {"face": "#A4B0B5", "inset": "#98A5AA", "backplane": "#8A979C",
                   "well": "#AEBBC0", "body": "#9CAAAF", "bodyAlt": "#8FA0A6",
                   "accent": "#0C8FA3", "line": "#4FA9BA", "hot": "#D4185C",
                   "lamp": "#14A46B", "mark": "#062229"},
        "palettes": {
            "ui": {"text": "#062229", "textDim": "#41707C", "textFaint": "#7BA1AB",
                   "accent": "#0C8FA3", "warn": "#A67207", "danger": "#D4185C", "ok": "#14A46B"},
            "surface": {"card": "#E2EAEDF2", "cardEdge": "#4FA9BA",
                        "divider": "#C9D8DD", "scrim": "#0622294D"},
        },
    },
    light_recipe={
        "families": {
            "Button": {"_ButtonColor": "$body", "_BorderColor": "$accent",
                       "_BorderRenderEmissive": 0.0, "_IconColor": "$accent",
                       "_IconRenderEmissive": 0.0, "_LightingAmbient": 0.58},
            "Knob": {"_KnobColor": "$body", "_FillColor": "$face",
                     "_OuterRing1Color": "$line", "_OuterRing1RenderEmissive": 0.0,
                     "_OuterRing2Color": "$accent", "_OuterRing2RenderEmissive": 0.0,
                     "_LineSublineFilledColor": "$accent",
                     "_LineSublineFilledRenderEmissive": 0.0,
                     "_LineSublineUnfilledColor": "#7C8E94",
                     "_LineSublineGlowEnabled": 0,
                     "_KnobNubColor": "$mark",
                     "_OuterMarksColorUnfilled": "#5F7178",
                     "_OuterMarksColorFilled": "$accent",
                     "_OuterMarksMajorColorUnfilled": "$line",
                     "_OuterMarksMajorColorFilled": "$mark",
                     "_OuterMarksRenderEmissive": 0.0, "_LightingAmbient": 0.58},
            "Slider": {"_HandleColor": "$mark", "_HandleRenderEmissive": 0.0,
                       "_BgColor": "$inset", "_TrackColor": "#7C8E94",
                       "_TrackValueFilledColor": "$accent",
                       "_TrackValueFilledRenderEmissive": 0.0,
                       "_TrackValueUnfilledColor": "#7C8E94",
                       "_BorderColor": "$line", "_BorderRenderEmissive": 0.0,
                       "_LightingAmbient": 0.58},
            "Toggle": {"_HandleColor": "$line", "_HandleRenderEmissive": 0.0,
                       "_BgColor": "$inset", "_TrackColor": "#7C8E94",
                       "_BorderColor": "$line", "_BorderRenderEmissive": 0.0,
                       "_LightingAmbient": 0.58},
            # Grid OFF in light mode. The HexGrid pattern BRIGHTENS its cells, which on a dark
            # floor reads as a faint etched watermark but on a pale one becomes a field of hard
            # white squares that swamps everything sitting on top. The glowing borders carry the
            # Tron identity on their own — "same lines, inverted floor" is about the LINES.
            "Panel": {"_PanelColor": "$face", "_BorderColor": "$line",
                      "_BorderRenderEmissive": 0.0, "_LightingAmbient": 0.74,
                      "_PanelPatternEnabled": 0},
        },
        "roles": {
            "pad": {"_ButtonColor": "$bodyAlt", "_BorderColor": "$line"},
            "panel.inset": {"_PanelColor": "$inset", "_BorderColor": "$line"},
            "panel.backplane": {"_PanelColor": "$backplane", "_BorderColor": "#6C7E84"},
            "display.well": {"_PanelColor": "$well", "_BorderColor": "$accent",
                             "_PanelRenderEmissive": 0.0},
            "button.accent": {"_ButtonColor": "#8FAAB1", "_BorderColor": "$accent",
                              "_IconColor": "$accent"},
            "button.hero": {"_ButtonColor": "#8FAAB1", "_BorderColor": "$accent",
                            "_IconColor": "$accent"},
            "lamp": {"_ButtonColor": "$backplane", "_BorderColor": "$line",
                     "_IconColor": "$line"},
        },
    },
)

# ── FLAT ─────────────────────────────────────────────────────────────────────
recipe(
    "Flat", "Flat", 4,
    "Ink and slate. No bevel, no shadow, no glow — just area and contrast.",
    dark={
        "trackTheme": "Nebula",
        "blurb": "Ink and slate. The quietest the app gets.",
        "colors": {"face": "#20242A", "inset": "#191D22", "backplane": "#12151A",
                   "well": "#151A20", "body": "#39404A", "bodyAlt": "#2C323A",
                   "accent": "#4C9EF0", "line": "#454D57", "hot": "#E8584C",
                   "lamp": "#4FCB86", "mark": "#F0F3F7"},
        "palettes": {
            "ui": {"text": "#F0F3F7", "textDim": "#8A929C", "textFaint": "#5C636D",
                   "accent": "#4C9EF0", "warn": "#F0A93E", "danger": "#E8584C", "ok": "#4FCB86"},
            "surface": {"card": "#20242AFA", "cardEdge": "#454D57",
                        "divider": "#191D22", "scrim": "#0A0C0FBF"},
        },
    },
    light={
        "trackTheme": "Rosewater",
        "blurb": "Paper white. Reads in daylight, on a phone, outdoors.",
        "colors": {"face": "#A8ACB2", "inset": "#9CA0A6", "backplane": "#8E9298",
                   "well": "#B4B8BE", "body": "#969BA2", "bodyAlt": "#868B93",
                   "accent": "#1E6FD9", "line": "#C3C8CE", "hot": "#CE3B2F",
                   "lamp": "#1E9A5E", "mark": "#12161B"},
        "palettes": {
            "ui": {"text": "#12161B", "textDim": "#5A616B", "textFaint": "#8B929B",
                   "accent": "#1E6FD9", "warn": "#9A6410", "danger": "#CE3B2F", "ok": "#1E9A5E"},
            "surface": {"card": "#FFFFFFFA", "cardEdge": "#C3C8CE",
                        "divider": "#E4E7EB", "scrim": "#12161B99"},
        },
    },
    light_recipe={
        "families": {
            "Button": {"_ButtonColor": "$body", "_BorderColor": "$line",
                       "_IconColor": "$mark", "_LightingAmbient": 0.58},
            "Knob": {"_KnobColor": "$body", "_FillColor": "$inset",
                     "_LineSublineFilledColor": "$accent",
                     "_LineSublineUnfilledColor": "$line",
                     "_KnobNubColor": "$mark", "_LightingAmbient": 0.58},
            "Slider": {"_HandleColor": "$mark", "_BgColor": "$inset",
                       "_TrackColor": "$line", "_TrackValueFilledColor": "$accent",
                       "_TrackValueUnfilledColor": "$line", "_LightingAmbient": 0.58},
            "Toggle": {"_HandleColor": "$mark", "_BgColor": "$inset",
                       "_TrackColor": "$line", "_LightingAmbient": 0.58},
            "Panel": {"_PanelColor": "$face", "_BorderColor": "$line",
                      "_LightingAmbient": 0.74},
        },
        "roles": {
            "pad": {"_ButtonColor": "$bodyAlt"},
            "panel.inset": {"_PanelColor": "$inset"},
            "panel.backplane": {"_PanelColor": "$backplane"},
            "display.well": {"_PanelColor": "$well"},
            "button.accent": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF",
                              "_BorderColor": "$accent"},
            "button.hero": {"_ButtonColor": "$accent", "_IconColor": "#FFFFFF",
                            "_BorderColor": "$accent"},
            "lamp": {"_ButtonColor": "$inset", "_IconColor": "$line"},
        },
    },
)

print("recipes written")
